theme: jekyll-theme-cayman
title: Information for makers of DYI ventilators
google_analytics: UA-164129921-1
designs_href: ./designs.html
show_designs_en: Show designs
cover_img: https://github.com/harmittaa/imandst-hackathon-ventilator-docs/blob/master/_images/cover_image.jpeg